bd_trama/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trama/', include('trama.urls'))
]

trama/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path("^$", views.index, name="index"),

    # 1.- vista detalle de una obra
    re_path(r"^obra/(?P<obra_id>\d+)/$",
            views.obra, name="detalle_obra"),

    # 2.- buscador
    re_path(r"^search/$", views.search, name="search"),

    # 3.- resultados de la búsqueda
    re_path(r"^search_result/$", views.search_result, name="search_result"),

    # 4.- listado de toda la BD (sin parámetros de búsqueda)
    re_path(r"^listado/$", views.listado, name="listado"),

    # 4 bis.- listado de autores de la BD (sin parámetros de búsqueda)
    re_path(r"^listado_autores/$", views.listado_autores,
            name="listado_autores"),

    # 4 tris.- listado de trabajos de la BD (sin parámetros de búsqueda)
    re_path(r"^trabajos/$", views.listado_trabajos,
            name="listado_trabajos"),

    # 5.- "acerca de", página estática
    re_path(r"^acerca/$", views.acerca, name="acerca"),

    # 6.- administrador
    re_path(r"^administrar/$", views.administrar, name="administrar"),
]

trama/models.py
from django.db import models


class Estilo(models.Model):
    nombre_estilo = models.CharField(
        max_length=256,
        blank=False,
        null=False,
        help_text="Nombre del estilo artítico (Renacimiento, barroco, etc.)")

    def __str__(self):
        return self.nombre_estilo


class TipoDeObra(models.Model):
    nombre_tipo = models.CharField(
        max_length=256,
        blank=False,
        null=False,
        help_text="Tipo de obra: Pintura, Escultura,...")

    def __str__(self):
        return self.nombre_tipo


class TrabajoRepresentado(models.Model):
    nombre_trabajo = models.CharField(
        max_length=256,
        blank=False,
        null=False,
        help_text="Nombre de la profesión representada (hilandera, curandera,...)")

    def __str__(self):
        return self.nombre_trabajo


class Autor(models.Model):
    nombre = models.CharField(max_length=256,
                              blank=False,
                              null=False,
                              help_text="Autor de la obra")
    alias = models.CharField(max_length=256,
                             blank=True,
                             null=True,
                             help_text="Alias u otros nombres por los que el artista es conocido"
                             )

    def __str__(self):
        return self.nombre


class Obra(models.Model):
    nombre_obra = models.CharField(
        max_length=256,
        blank=False,
        null=False,
        help_text="Nombre completo de la obra")
    autor = models.ForeignKey(
        Autor,
        blank=False,
        null=False,
        on_delete=models.CASCADE)
    anno = models.CharField("Año o época aproximada de la obra",
                            max_length=64,
                            blank=False,
                            null=False,
                            help_text="Año (exacto o aproximado) de creación de la obra")
    ubicacion = models.CharField("Ubicación",
                                 max_length=128,
                                 blank=False,
                                 null=False,
                                 help_text="Ubicación de la obra (museo, colección particular...)")
    iconografia = models.CharField("Iconografía",
                                   max_length=128,
                                   blank=False,
                                   null=False,
                                   help_text="Breve descripción de la iconografía representada")
    descripcion = models.TextField("Descripción",
                                   blank=False,
                                   null=False,
                                   help_text="Descripción de la obra en texto libre")
    url_externa = models.CharField(max_length=512,
                                   blank=True,
                                   null=True,
                                   help_text="URL con contexto")
    url_imagen = models.CharField(max_length=512,
                                  blank=True,
                                  null=True,
                                  help_text="URL externa del archivo de imagen (si la hay)")
    estilo = models.ForeignKey(
        Estilo,
        blank=False,
        null=False,
        on_delete=models.CASCADE)
    tipo_de_obra = models.ForeignKey(
        TipoDeObra,
        blank=False,
        null=False,
        on_delete=models.CASCADE)
    trabajo_representado = models.ManyToManyField(
        TrabajoRepresentado,
        blank=False)

    def __str__(self):
        return f"{self.nombre_obra} ({self.autor})"

trama/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render

from trama.models import Autor, Obra, TrabajoRepresentado
from trama.utils.buscador import Buscador


def index(request):
    return render(request, "index.html")


def administrar(request):
    return render(request, "index.html")


def search(request):
    return render(request, "search.html")


def _paginated_listado(request, modelo, template):
    num_per_page = 10
    obras = Paginator(modelo.objects.all().order_by("id"), num_per_page)
    page_number = request.GET.get("pagina")
    if page_number is None:
        page_number = 1
    else:
        # Todo check if `page_number` is a positive integer and if not,
        # return a 404
        page_number = int(page_number)
    offset = (page_number - 1)*num_per_page
    pagina_obj = obras.get_page(page_number)
    return render(request, template,
                  {"result": pagina_obj,
                   "offset": offset})


def listado(request):
    return _paginated_listado(request, Obra, "listado.html")


def listado_autores(request):
    autores = Autor.objects.all().order_by("id")
    return render(request, "listado_autores.html",
                  {"autores": autores})


def search_result(request):
    if request.method == "GET":
        query_text = request.GET.get("query", "")
        buscador = Buscador(query_text=query_text)
        query_results = buscador.get()
        return render(request, "search.html",
                      {"query": query_text,
                       "query_result": query_results})


def acerca(request):
    return render(request, "acerca.html")


def obra(request, obra_id):
    obra = get_object_or_404(Obra, pk=obra_id)
    return render(request, "obra.html", {"obra": obra})


def listado_trabajos(request):
    num_obras = len(Obra.objects.all())
    trabajos = TrabajoRepresentado.objects.annotate(
        num_obras=Count('obra')
    ).annotate(perc=100*Count('obra') / num_obras
               ).filter(num_obras__gt=0).order_by("-num_obras")
    return render(request, "listado_trabajos.html",
                  {"trabajos": trabajos})

trama/templates/acerca.html
{% extends "base.html" %}

{% block texto_barra %}Acerca de{% endblock %}

{% block content %}

<div class="container">
<p>Este trabajo forma parte del Proyecto I+D <em>Los trabajos de las mujeres en la Andalucía Moderna, TRAMA</em>.</p>

<p>TRAMA está financiado por el Programa FEDER (B-HUM-724-UGR20)</p>

Investigadoras principales:
<a href="https://www.ugr.es/personal/margarita-maria-birriel-salcedo">Margarita María Birriel Salcedo</a> e
<a href="https://hmoderame.ugr.es/pages/profesorado/area-historia-moderna/catedratica">Inmaculada Arias de Saavedra Alías</a>.
</div>
{% endblock %}

trama/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Base de datos del proyecto TRAMA" />
        <meta name="author" content="Proyecto TRAMA" />
        <title>Proyecto Trama</title>
        <!-- Favicon-->
        <!--<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />-->
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'trama/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container px-4 px-lg-5 h-10" style="height: 100px;"> 
                <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'trama/trama_imgs/2. Horizontal/jpg/Blanco y negro/trama_Horizontal negro.jpg' %}"
                    class="img-fluid" style="max-height: 110px;"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"><!-- --></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        {% block tab_inicio %}<li class="nav-item"><a class="nav-link" href="{% url 'index' %}"><i class="bi bi-house-door"><!-- --></i> Inicio</a></li>{% endblock %}
                        {% block tab_buscador %}<li class="nav-item"><a class="nav-link" href="{% url 'search' %}"><i class="bi bi-binoculars"><!-- --></i> Buscador</a></li>{% endblock %}
                        {% block tab_listado %}<li class="nav-item"><a class="nav-link" href="{% url 'listado' %}"><i class="bi bi-card-list"><!-- --></i> Obras</a></li>{% endblock %}
                        {% block tab_autores %}<li class="nav-item"><a class="nav-link" href="{% url 'listado_autores' %}"><i class="bi bi-palette"><!-- --></i> Autores</a></li>{% endblock %}
                        {% block tab_trabajos %}<li class="nav-item"><a class="nav-link" href="{% url 'listado_trabajos' %}"><i class="bi bi-tools"><!-- --></i> Trabajos</a></li>{% endblock %}
                        {% block tab_admin %}<li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}"><i class="bi bi-lock"><!-- --></i> Admin</a></li>{% endblock %}
                        {% block tab_acerca %}<li class="nav-item"><a class="nav-link" href="{% url 'acerca' %}"><i class="bi bi-book"><!-- --></i> Acerca de</a></li>{% endblock %}                    
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Header-->
        <header class="bg-dark py-1">
            <div class="container px-4 px-lg-5 h-10 my-1">
                <div class="text-white">
                    <h1 class="display-6 fw-bolder">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{% block texto_barra %}Proyecto TRAMA{% endblock %}</h1>
                </div>
            </div>
        </header>

            <section class="py-4">
                <div class="container px-4 px-lg-5 mt-2 ml-5">
                    <!-- <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center"> -->
                     {% block content %} {% endblock %}
                    <!-- </div> -->
                </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">&copy; Copyright Proyecto TRAMA 2022 - <a href="https://twitter.com/TramaUGR" class="text-white">Síguenos en Twitter</a>
</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'trama/scripts.js' %}"></script>
    </body>
</html>

trama/templates/index.html
{% extends "base.html" %}{% load static %}

{% block texto_barra %}Inicio{% endblock %}

{% block content %}
<div class="row">
    <img src="{% static 'trama/imagen_portada.jpg' %}"
    class="img-fluid img-thumbnail float-left col-sm-1 col-md-2 col-xs-12"/>
<div class="float-left col-sm-10 col-md-10 col-xs-12 mt-5 px-5">
    <p>
    En esta web se aloja una base de datos fruto del trabajo realizado en el proyecto
<em>Los trabajos de las mujeres en la Andalucía Moderna, TRAMA</em>. Programa FEDER (B-HUM-724-UGR20).
</p>
<p>
En ella se han registrado obras de arte de muy diversa naturaleza, propias de la Edad Moderna y
ajustadas al ámbito andaluz en las que se pueden advertir a mujeres realizando diversos trabajos.
</p>
</div>


</div>
 
{% endblock %}

trama/templates/listado.html
{% extends "base.html" %}

{% block texto_barra %}Listado completo de obras{% endblock %}

{% block content %}

    <table class="table table-striped table-hover">
      <caption class="text-center">
        <span class="step-links">
            {% if result.has_previous %}
                <a href="?pagina=1" class="link-secondary"><i class="bi bi-chevron-double-left"><!-- --></i></a>
                <a href="?pagina={{ result.previous_page_number }}" class="link-secondary"><i class="bi bi-chevron-left"><!-- --></i></a>
                {% endif %}
  
                <span class="current">
                  Página {{ result.number }} de {{ result.paginator.num_pages }}.
                </span>
  
              {% if result.has_next %}
                  <a href="?pagina={{ result.next_page_number }}" class="link-secondary"><i class="bi bi-chevron-right"><!-- --></i></a>
                  <a href="?pagina={{ result.paginator.num_pages }}" class="link-secondary"><i class="bi bi-chevron-double-right"><!-- --></i>
                  </a>
              {% endif %}
        </span>
      </caption>
    <thead>
      <tr>
        <th>Nº</th>
        <th>Nombre de obra</th>
        <th>Autor</th>
        <th>Enlace</th>
      </tr>
    </thead>
    <tbody>
    {% for obra in result %}
    <tr>
      <td><strong>{{offset|add:forloop.counter}}</strong> de
        <strong>{{result.paginator.count}}</strong></td>
      <td><em>{{obra.nombre_obra}}</em></td>
      <td>{{obra.autor.nombre}}</td>
      <td><a href="{% url 'detalle_obra' obra.pk %}">Ir a obra <i class="bi bi-search"><!-- --></i></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock %}

trama/templates/listado_autores.html
{% extends "base.html" %}

{% block texto_barra %}Listado completo de autores{% endblock %}

{% block content %}
    <table class="table table-striped table-hover">
      <caption>Número de autores / grupos presentes en la base de datos: <strong>{{autores.count}}</strong>.</caption>
    <thead>
      <tr>
        <th>Id</th>
        <th>Nombre del autor / escuela / grupo</th>
        <th>Nº de obras en la base de datos</th>
        <th>Obras</th>
      </tr>
    </thead>
    <tbody>
    {% for autor in autores %}
    <tr>
      <td rowspan="{{autor.obra_set.all|length}}">{{forloop.counter}}</td>
      <td rowspan="{{autor.obra_set.all|length}}">{{autor.nombre}}</td>
      <td rowspan="{{autor.obra_set.all|length}}"><strong>{{autor.obra_set.all|length}}</strong></td>
        {% for obra in autor.obra_set.all %}
          {% if forloop.counter != 1 %}
          <tr>
          {% endif %}
          <td>
          <em>{{obra.nombre_obra}}</em> ({{obra.anno}}) <a href="{% url 'detalle_obra' obra.pk %}"> <i class="bi bi-search"><!-- --></i></a>
          </td>
          </tr>

        {% endfor %}

    {% endfor %}
    </tbody>
    </table>

{% endblock %}

trama/templates/listado_trabajos.html
{% extends "base.html" %}

{% block texto_barra %}Listado completo de trabajos{% endblock %}

{% block content %}
    <table class="table table-striped table-hover">
      <caption>Número de trabajos representados en la base de datos: <strong>{{trabajos.count}}</strong>.</caption>
    <thead>
      <tr>
        <th>Id</th>
        <th>Nombre del trabajo</th>
        <th>Nº de obras en la base de datos</th>
        <th>Porcentaje</th>
      </tr>
    </thead>
    <tbody>
    {% for trabajo in trabajos %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{trabajo.nombre_trabajo}} <a href="{% url 'search_result' %}?query={{trabajo.nombre_trabajo}}"><i class="bi bi-binoculars"></i></a></td>
      <td>{{trabajo.num_obras}}</td>
      <td>{{trabajo.perc}}%</td>
    </tr>

    {% endfor %}
    </tbody>
    </table>

{% endblock %}

trama/templates/obra.html
{% extends "base.html" %}{% load static %}{% load admin_urls %}

{% block texto_barra %}Detalle de obra{% endblock %}


{% block content %}
    <div class="container-fluid">
        <h2>{{obra.nombre_obra}} <a class="btn btn-secondary"
            href="{% url 'admin:trama_obra_change' obra.pk %}"><i class="bi bi-pencil"></i></a></h2>
        
    </div>  
        <div class="container-fluid">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td scope="row" rowspan="0">
                            {% if obra.url_imagen %}
                                <a href="{{obra.url_imagen}}"><img
                                    src="{{obra.url_imagen}}" class="img-fluid"
                                    style="vertical-align: middle;"
                                style="max-height: 200px;"/></a>
                            {% else %}
                                <img src="{% static 'trama/sin_imagen.jpg' %}" />
                            {% endif %}
                        </td>
                        <td scope="row"><strong>Nombre</strong></td>
                        <td scope="row"><em>{{obra.nombre_obra}}</em></td>
                    </tr>
                    <tr>
                        <td scope="row"><strong>Autor</strong></td>
                        <td scope="row">{{obra.autor.nombre}}</td>
                    </tr>
                    <tr>
                        <td scope="row"><strong>Año / época</strong></td>
                        <td scope="row">{{obra.anno}}</td>
                    </tr>
                    <tr>
                        <td scope="row"><strong>Ubicación</strong></td>
                        <td scope="row">{{obra.ubicacion}}</td>
                    </tr>
                    <tr>
                        <td scope="row"><strong>Tipo de obra</strong></td>
                        <td scope="row">{{obra.tipo_de_obra.nombre_tipo}}</td>
                    </tr>
                    <tr>
                        <td scope="row"><strong>Estilo</strong></td>
                        <td scope="row">{{obra.estilo.nombre_estilo}}
                        <a href="{% url 'search_result' %}?query={{obra.estilo.nombre_estilo}}"><i class="bi bi-binoculars"></i></a></td>
                    </tr>
                    <tr>
                        <td scope="row"><strong>Iconografía</strong></td>
                        <td scope="row">{{obra.iconografia}}</td>
                    </tr>
                    <tr>
                        <td scope="row" rowspan="{{obra.trabajo_representado.all.count}}"><strong>Trabajos representados</strong> ({{obra.trabajo_representado.all.count}})</td>
                        {% for trabajo in obra.trabajo_representado.all %}
                        <td scope="row">{{ trabajo.nombre_trabajo }}
                            <a href="{% url 'search_result' %}?query={{trabajo.nombre_trabajo}}"><i class="bi bi-binoculars"></i></a>
                        </td></tr>
                        <tr>{% endfor %}
                    </tr>
                    <tr>
                        <td scope="row"><strong>Descripción</strong></td>
                        <td scope="row">{{obra.descripcion}}</td>
                    </tr>
                    {% if obra.url_externa %}
                    <tr>
                        <td scope="row"><strong>URL externa</strong></td>
                        <td scope="row"><a href="{{obra.url_externa}}"><i class="bi bi-box-arrow-up-right"></i></a></td>
                    </tr>
                    {% endif %} 
            </table>
        </div>
{% endblock %}

trama/templates/search.html
{% extends "base.html" %}

{% block texto_barra %}Buscador{% endblock %}

{% block content %}

  {%if query %}
    <table class="table table-striped">
      <caption class="text-center">Consulta: <strong>'{{query}}'</strong>.
        Número de obras encontradas:  <strong>{{query_result|length}}</strong></caption>
        <thead>
          <tr>
            <th>Id</th>
            <th>Nombre de la obra</th>
            <th>Autor</th>
            <th>Relevancia</th>
            <th>Ir a detalle</th>
          </tr>
        </thead>
        <tbody>
          {% for obra, score in query_result %}
      <tr>
        <td>{{obra.id}}</td>
        <td><em>{{obra.nombre_obra}}</em></td>
        <td>{{obra.autor}}</td>
        <td>{{score}}%</td>
        <td><a href="{% url 'detalle_obra' obra.pk %}" alt="Mostrar detalle"><i class="bi bi-search"></i></a></td>
      </tr>
    {% endfor %}</tbody>
    </table>

  {% else %}
      <form action="{% url 'search_result' %}" method="GET" id="form1">
        <div class="form-group container">
        <fieldset>
          <div class="mx-sm-3 mb-2 row">
            <div class="col-sm-1 col-md-1 col-xs-1"></div>
          <input type="text" id="query" name="query"
          class="float-left col-sm-5 col-md-5 col-xs-5"/>
          <div class="col-sm-1 col-md-1 col-xs-1"></div>
          <input type="submit" value="Buscar" class="btn-light ma-2 mb-2 float-left col-sm-1 col-md-1 col-xs-1" />
         </div>
        </fieldset>
        </div>
     </form>
  {% endif %}
{% endblock %}